### ISSUE TITLE
fazer um read.me maravilhoso como apenas a Levzinha sabe fazer

### ISSUE THREAD

**Issue by pachicodes** [feministech/feministech#1]
Estimada @levxyca 
Venho por meio desse, solicitar os seus talentos, na criacao do read,me desse e de outros projetos, porque voce eh a rainha absoluta dos readmes

**Comment by levxyca** [comment]
Seus pedidos são feitos com todo carinho caríssima @pachicodes 
Inclusive a primeira versão desse readme se encontra criada nesse momento, atualizaremos ele conforme formos tendo mais informações para acrescentar
Dito isso, irei fechar essa digníssima issue!
