### ISSUE TITLE
Trocar a foto da Patrícia

### ISSUE THREAD

**Issue by patriciaverso** [feministech/feministech#45]
# Eu vi ela na rua e ela nem estava de cabelo comprido nem de chapéu de Festa Junina. Isso é propaganda enganosa!

**Comment by pfanovaes** [comment]
Batata

**Comment by pfanovaes** [comment]
Fotos na internet confirmam, esse cabelo é fake.

**Comment by mocraveirodev** [comment]
Passei do lado dela e não levei uma cantada... Essa Patrícia é fake!

**Comment by pfanovaes** [comment]
> Passei do lado dela e não levei uma cantada... Essa Patrícia é fake!

Ahá, nem eu, achei que era pq eu sou feia.

**Comment by lissarubi** [comment]
Falsidade ideológica! estei convocando uma reunião na coordenação para banirmos essa criminosa!

**Comment by lissarubi** [comment]
carai, os comentário de cima tiraram completamente o contexto do meu, bom demais kkkkkkkkkkkkkk

**Comment by lissarubi** [comment]
Resolvido em #46
