### ISSUE TITLE
Ajustar a descrição da comunidade no site

### ISSUE THREAD

**Issue by morgannadev** [feministech/feministech#56]
Na página principal do site consta a seguinte descrição:
`A Feministech é um grupo de pessoas que se identificam no feminino e não-bináries que produzem, consomem e compartilham conteúdo sobre tecnologia, enquanto constroem uma comunidade diversa e inclusiva.`

Contudo, atualizamos a descrição para:
`(...) grupo **feminista** de pessoas que se identificam no feminino e não-bináries que compartilham conhecimento sobre tecnologia fazendo lives, escrevendo artigos, produzindo vídeos ou postagens, entre outros.`

Então devemos adicionar a palavra feminista na descrição conforme exemplo acima usado em todas as demais redes.

**Comment by ghost** [comment]
Obrigada por sinalizar @morgannadev, a descrição já foi corrigida pela @lissatransborda no PR #59 🧡
