### ISSUE TITLE
Adicionar texto alternativo nos links de redes sociais para melhorar acessibilidade 📎

### ISSUE THREAD

**Issue by ghost** [feministech/feministech#6]

**Comment by tabita-barbosa** [comment]
gostaria de ajudar nesse Issue!
Fiz algumas buscas e queria alinhar, a melhor forma para ler os links poderia ser, por exemplo: Link para nosso Facebook ou clique para ir ao nosso facebook ... ou outra sugestão, se houver

**Comment by lissarubi** [comment]
resolvido em #52
